from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.operator.wave1_ci_reproducibility_strategy import build_wave1_ci_reproducibility_strategy_receipt  # noqa: E402
from tools.operator.wave1_trust_surface_matrix import build_wave1_trust_surface_matrix  # noqa: E402


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _git(tmp_path: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(tmp_path), *args], text=True).strip()


def _commit_all(tmp_path: Path, message: str) -> str:
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-m", message)
    return _git(tmp_path, "rev-parse", "HEAD")


def _init_git_repo(tmp_path: Path) -> None:
    _git(tmp_path, "init")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test User")


def test_wave1_trust_surface_matrix_keeps_stale_binding_visible(tmp_path: Path) -> None:
    _init_git_repo(tmp_path)
    (tmp_path / "README.md").write_text("base\n", encoding="utf-8")
    head = _commit_all(tmp_path, "base")

    _write_json(
        tmp_path / "KT_PROD_CLEANROOM" / "reports" / "kt_sigstore_keyless_status.json",
        {
            "status": "PASS",
            "current_repo_head": "a" * 40,
            "declared_public_trust_path_for_pass": "sigstore_keyless_with_rekor_and_identity_constraints",
            "declared_ws11_keyless_surfaces": ["KT_PROD_CLEANROOM/reports/public_verifier_manifest.json"],
            "stronger_claim_not_made": ["no widening"],
        },
    )
    _write_json(tmp_path / "KT_PROD_CLEANROOM" / "reports" / "kt_sigstore_integration_receipt.json", {"status": "PASS"})
    _write_json(tmp_path / "KT_PROD_CLEANROOM" / "reports" / "kt_sigstore_publication_bundle.json", {"status": "PASS"})
    _write_json(tmp_path / "KT_PROD_CLEANROOM" / "reports" / "kt_rekor_inclusion_receipt.json", {"status": "PASS"})
    _write_json(
        tmp_path / "KT_PROD_CLEANROOM" / "reports" / "kt_supply_chain_policy_receipt.json",
        {
            "status": "PASS",
            "current_repo_head": head,
            "bounded_current_surface": "KT_PROD_CLEANROOM/reports/public_verifier_manifest.json",
            "stronger_claim_not_made": ["no widening"],
            "supply_chain_lineage": {
                "source_in_toto_ref": "KT_PROD_CLEANROOM/reports/source_build_attestation/in_toto_statement.json",
                "publication_in_toto_ref": "KT_PROD_CLEANROOM/reports/cryptographic_publication/in_toto_statement.json",
                "build_provenance_ref": "KT_PROD_CLEANROOM/reports/kt_build_provenance.dsse",
                "verification_summary_ref": "KT_PROD_CLEANROOM/reports/kt_verification_summary_attestation.dsse",
                "build_verification_receipt_ref": "KT_PROD_CLEANROOM/reports/kt_build_verification_receipt.json",
                "supply_chain_layout_ref": "KT_PROD_CLEANROOM/governance/supply_chain_layout.json",
            },
        },
    )
    _write_json(
        tmp_path / "KT_PROD_CLEANROOM" / "reports" / "kt_determinism_envelope_receipt.json",
        {"status": "PASS", "current_repo_head": head},
    )
    _write_json(
        tmp_path / "KT_PROD_CLEANROOM" / "governance" / "kt_tuf_distribution_policy.json",
        {"status": "ACTIVE", "current_repo_head": head, "scope": "CHILD_VERIFIER_DISTRIBUTION_ONLY", "distribution_targets": []},
    )
    _commit_all(tmp_path, "seed trust")

    report = build_wave1_trust_surface_matrix(root=tmp_path)

    assert report["status"] == "PASS"
    assert "sigstore_rekor_keyless" in report["stale_head_binding_visible_for"]


def test_wave1_ci_repro_strategy_prefers_hashed_lockfile_without_toolchain_sprawl(tmp_path: Path) -> None:
    _init_git_repo(tmp_path)
    (tmp_path / "KT_PROD_CLEANROOM").mkdir(parents=True, exist_ok=True)
    (tmp_path / "KT_PROD_CLEANROOM" / "pyproject.toml").write_text("[project]\nname='kt'\nversion='0.0.0'\n", encoding="utf-8")
    (tmp_path / "KT_PROD_CLEANROOM" / "pytest.ini").write_text("[pytest]\naddopts = -q\n", encoding="utf-8")
    (tmp_path / "KT_PROD_CLEANROOM" / "requirements-wave0.lock.txt").write_text(
        "# generated by pip-compile\npkg==1.0 --hash=sha256:abc\n",
        encoding="utf-8",
    )
    (tmp_path / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
    (tmp_path / ".github" / "workflows" / "ci_truth_barrier.yml").write_text(
        "steps:\n  - run: python -m pip install --require-hashes -r KT_PROD_CLEANROOM/requirements-wave0.lock.txt\n",
        encoding="utf-8",
    )
    _commit_all(tmp_path, "seed repro")

    report = build_wave1_ci_reproducibility_strategy_receipt(root=tmp_path)

    assert report["status"] == "PASS"
    assert report["local_dev_primary"] == "pip_compile_exact_hash_lockfile"
