from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence

from tools.verification.strict_json import load_no_dupes


SCHEMA_ID = "kt.lane_contract.prep_only.v0"
COMPILER_ID = "KT_LANE_COMPILER_V0"
AUTHORITY = "PREP_ONLY_TOOLING"
DEFAULT_REPORT_ROOT_REL = "KT_PROD_CLEANROOM/reports"

FORBIDDEN_AUTHORITY_TOKENS = (
    "LIMITED_RUNTIME_EXECUTION_AUTHORIZED",
    "LIMITED_RUNTIME_AUTHORIZED",
    "R6_OPEN",
    "RUNTIME_AUTHORIZED",
    "RUNTIME_CUTOVER_AUTHORIZED",
    "ACTIVATION_CUTOVER_EXECUTED",
    "LOBE_ESCALATION_AUTHORIZED",
    "PACKAGE_PROMOTION_AUTHORIZED",
    "PACKAGE_PROMOTION",
    "PROMOTE_PACKAGE",
    "COMMERCIAL_CLAIM_AUTHORIZED",
    "COMMERCIAL_CLAIMS_AUTHORIZED",
    "COMMERCIAL_ACTIVATION_CLAIM_AUTHORIZED",
)

FORBIDDEN_AUTHORITY_CONTEXT_EXEMPT_FIELDS = frozenset(
    {
        "must_not_authorize",
        "no_authorization_drift_checks",
        "future_blockers",
        "reason_codes",
        "artifacts",
        "json_parse_inputs",
        "authoritative_inputs",
        "prep_only_outputs",
    }
)

PREP_ONLY_BANNER = (
    "PREP_ONLY: generated by KT_LANE_COMPILER_V0 as tooling/prep. "
    "This scaffold does not authorize runtime, R6 open, package promotion, or commercial claims."
)

REQUIRED_SPEC_FIELDS = (
    "lane_id",
    "lane_name",
    "authority",
    "owner",
    "summary",
    "operator_path",
    "test_path",
    "artifacts",
)


class LaneSpecError(ValueError):
    """Raised when a lane spec is missing prep-only contract requirements."""


def _stable_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def _as_text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise LaneSpecError(f"{field} must be a non-empty string")
    return value.strip()


def _as_string_list(value: Any, field: str, *, allow_empty: bool = False) -> List[str]:
    if not isinstance(value, list):
        raise LaneSpecError(f"{field} must be a list of strings")
    result = []
    for index, item in enumerate(value):
        if not isinstance(item, str) or not item.strip():
            raise LaneSpecError(f"{field}[{index}] must be a non-empty string")
        result.append(item.strip())
    if not result and not allow_empty:
        raise LaneSpecError(f"{field} must not be empty")
    return sorted(result)


def _optional_string_list(spec: Mapping[str, Any], field: str) -> List[str]:
    if field not in spec:
        return []
    return _as_string_list(spec[field], field, allow_empty=True)


def _as_safe_lane_id(value: Any, field: str) -> str:
    lane_id = _as_text(value, field)
    if any(char not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-" for char in lane_id):
        raise LaneSpecError(f"{field} must use only letters, digits, underscores, or hyphens")
    if ".." in lane_id:
        raise LaneSpecError(f"{field} must not contain traversal tokens")
    return lane_id


def _as_safe_relpath(value: Any, field: str, *, required_prefix: str) -> str:
    raw = _as_text(value, field).replace("\\", "/")
    path = Path(raw)
    if path.is_absolute() or ".." in path.parts:
        raise LaneSpecError(f"{field} must be a safe relative path")
    if not raw.startswith(required_prefix):
        raise LaneSpecError(f"{field} must start with {required_prefix}")
    return raw


def _forbidden_hits(values: Iterable[Any]) -> List[str]:
    text = json.dumps(list(values), sort_keys=True, ensure_ascii=True).upper()
    return sorted(token for token in FORBIDDEN_AUTHORITY_TOKENS if token in text)


def _forbidden_hits_by_field(values: Mapping[str, Any]) -> Dict[str, List[str]]:
    hits: Dict[str, List[str]] = {}
    for field, value in values.items():
        if field in FORBIDDEN_AUTHORITY_CONTEXT_EXEMPT_FIELDS:
            continue
        field_hits = _forbidden_hits([value])
        if field_hits:
            hits[field] = field_hits
    return hits


def _safe_function_name(lane_id: str) -> str:
    chars = [char.lower() if char.isalnum() else "_" for char in lane_id]
    compact = "_".join(part for part in "".join(chars).split("_") if part)
    return compact or "compiled_lane"


def _normalize_spec(spec: Mapping[str, Any]) -> Dict[str, Any]:
    missing = [field for field in REQUIRED_SPEC_FIELDS if field not in spec]
    if missing:
        raise LaneSpecError(f"missing required fields: {', '.join(sorted(missing))}")

    authority = _as_text(spec["authority"], "authority")
    if authority != AUTHORITY:
        raise LaneSpecError(f"authority must be {AUTHORITY}")

    normalized = {
        "lane_id": _as_safe_lane_id(spec["lane_id"], "lane_id"),
        "lane_name": _as_text(spec["lane_name"], "lane_name"),
        "authority": authority,
        "owner": _as_text(spec["owner"], "owner"),
        "summary": _as_text(spec["summary"], "summary"),
        "operator_path": _as_safe_relpath(
            spec["operator_path"],
            "operator_path",
            required_prefix="KT_PROD_CLEANROOM/tools/operator/",
        ),
        "test_path": _as_safe_relpath(
            spec["test_path"],
            "test_path",
            required_prefix="KT_PROD_CLEANROOM/tests/operator/",
        ),
        "artifacts": _as_string_list(spec["artifacts"], "artifacts"),
        "json_parse_inputs": _optional_string_list(spec, "json_parse_inputs"),
        "no_authorization_drift_checks": _optional_string_list(spec, "no_authorization_drift_checks"),
        "future_blockers": _optional_string_list(spec, "future_blockers"),
        "reason_codes": _optional_string_list(spec, "reason_codes"),
        "lane_kind": _as_text(spec["lane_kind"], "lane_kind") if "lane_kind" in spec else "PREP",
        "current_main_head": _as_text(spec["current_main_head"], "current_main_head")
        if "current_main_head" in spec
        else "",
        "predecessor_outcome": _as_text(spec["predecessor_outcome"], "predecessor_outcome")
        if "predecessor_outcome" in spec
        else "",
        "selected_outcome": _as_text(spec["selected_outcome"], "selected_outcome") if "selected_outcome" in spec else "",
        "next_lawful_move": _as_text(spec["next_lawful_move"], "next_lawful_move")
        if "next_lawful_move" in spec
        else "",
        "may_authorize": _optional_string_list(spec, "may_authorize"),
        "must_not_authorize": _optional_string_list(spec, "must_not_authorize"),
        "authoritative_inputs": _optional_string_list(spec, "authoritative_inputs"),
        "prep_only_outputs": _optional_string_list(spec, "prep_only_outputs"),
    }

    forbidden = _forbidden_hits_by_field(normalized)
    if forbidden:
        detail = "; ".join(f"{field}: {', '.join(tokens)}" for field, tokens in sorted(forbidden.items()))
        raise LaneSpecError(
            "spec contains forbidden authority tokens outside explicit negative/prep fields: " + detail
        )

    return normalized


def validate_lane_spec(spec: Mapping[str, Any]) -> Dict[str, Any]:
    """Validate and normalize a lane spec without executing or authorizing anything."""

    return _normalize_spec(spec)


def _operator_skeleton(spec: Mapping[str, Any]) -> str:
    function_name = _safe_function_name(str(spec["lane_id"]))
    return (
        "from __future__ import annotations\n\n"
        "from typing import Any, Dict, Mapping\n\n\n"
        f"LANE_ID = {spec['lane_id']!r}\n"
        f"AUTHORITY = {AUTHORITY!r}\n"
        f"PREP_ONLY_BANNER = {PREP_ONLY_BANNER!r}\n\n\n"
        f"def build_{function_name}_prep_packet(spec: Mapping[str, Any]) -> Dict[str, Any]:\n"
        "    return {\n"
        f"        \"lane_id\": {spec['lane_id']!r},\n"
        "        \"authority\": AUTHORITY,\n"
        "        \"status\": \"PREP_ONLY_SCAFFOLD\",\n"
        "        \"prep_only_banner\": PREP_ONLY_BANNER,\n"
        "        \"input_spec\": dict(sorted(spec.items())),\n"
        "    }\n"
    )


def _test_skeleton(spec: Mapping[str, Any]) -> str:
    function_name = _safe_function_name(str(spec["lane_id"]))
    return (
        "from __future__ import annotations\n\n\n"
        f"def test_{function_name}_prep_only_boundary() -> None:\n"
        f"    assert {AUTHORITY!r} == \"PREP_ONLY_TOOLING\"\n"
        "    assert \"authorize runtime\" not in \"prep only tooling\"\n"
    )


def _artifact_list(spec: Mapping[str, Any]) -> Dict[str, Any]:
    return {
        "schema_id": "kt.lane_artifact_list.prep_only.v0",
        "compiler_id": COMPILER_ID,
        "authority": AUTHORITY,
        "lane_id": spec["lane_id"],
        "prep_only_banner": PREP_ONLY_BANNER,
        "artifacts": list(spec["artifacts"]),
    }


def _reason_code_scaffold(spec: Mapping[str, Any]) -> Dict[str, Any]:
    codes = spec["reason_codes"] or ["PREP_ONLY_NOT_AUTHORIZED", "NO_AUTHORIZATION_DRIFT"]
    return {
        "schema_id": "kt.lane_reason_code_scaffold.prep_only.v0",
        "compiler_id": COMPILER_ID,
        "authority": AUTHORITY,
        "lane_id": spec["lane_id"],
        "reason_codes": [
            {
                "code": code,
                "classification": "PREP_ONLY",
                "meaning": "Operator must fill before any authoritative lane consumes this scaffold.",
            }
            for code in codes
        ],
    }


def _json_parse_list(spec: Mapping[str, Any]) -> Dict[str, Any]:
    return {
        "schema_id": "kt.lane_json_parse_list.prep_only.v0",
        "compiler_id": COMPILER_ID,
        "authority": AUTHORITY,
        "lane_id": spec["lane_id"],
        "json_parse_inputs": list(spec["json_parse_inputs"]),
    }


def _no_authorization_drift_checks(spec: Mapping[str, Any]) -> Dict[str, Any]:
    checks = spec["no_authorization_drift_checks"] or [
        "Generated lane remains PREP_ONLY_TOOLING.",
        "Generated artifacts contain no limited-runtime authorization claim.",
        "Generated artifacts contain no R6 open, package promotion, or commercial claim authorization.",
    ]
    return {
        "schema_id": "kt.lane_no_authorization_drift_checks.prep_only.v0",
        "compiler_id": COMPILER_ID,
        "authority": AUTHORITY,
        "lane_id": spec["lane_id"],
        "forbidden_authority_tokens": list(FORBIDDEN_AUTHORITY_TOKENS),
        "checks": list(checks),
    }


def _future_blocker_register(spec: Mapping[str, Any]) -> Dict[str, Any]:
    blockers = spec["future_blockers"] or ["AUTHORITATIVE_PACKET_NOT_YET_AUTHORED"]
    return {
        "schema_id": "kt.lane_future_blocker_register.prep_only.v0",
        "compiler_id": COMPILER_ID,
        "authority": AUTHORITY,
        "lane_id": spec["lane_id"],
        "blockers": [
            {
                "blocker_id": blocker,
                "status": "OPEN",
                "resolution_authority": "future authoritative lane only",
            }
            for blocker in blockers
        ],
    }


def _pr_body(spec: Mapping[str, Any], *, replay: bool) -> str:
    title = "Replay Prep PR" if replay else "Prep PR"
    replay_line = "Replay scope: deterministic re-generation from the same prep-only lane spec." if replay else (
        "Scope: initial tooling/prep scaffold generation."
    )
    return (
        f"# {title}: {spec['lane_id']}\n\n"
        f"{PREP_ONLY_BANNER}\n\n"
        f"Lane: {spec['lane_name']}\n\n"
        f"Owner: {spec['owner']}\n\n"
        f"Summary: {spec['summary']}\n\n"
        f"{replay_line}\n\n"
        "Authority boundary:\n"
        "- Does not authorize runtime.\n"
        "- Does not open R6.\n"
        "- Does not promote packages.\n"
        "- Does not authorize commercial claims.\n"
    )


def build_lane_contract(spec: Mapping[str, Any]) -> Dict[str, Any]:
    """Build a deterministic prep-only lane contract dictionary."""

    normalized = validate_lane_spec(spec)
    lane_slug = _safe_function_name(str(normalized["lane_id"]))
    files = {
        normalized["operator_path"]: _operator_skeleton(normalized),
        normalized["test_path"]: _test_skeleton(normalized),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_artifact_list__{lane_slug}.json": _stable_json(
            _artifact_list(normalized)
        ),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_reason_codes__{lane_slug}.json": _stable_json(
            _reason_code_scaffold(normalized)
        ),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_json_parse_list__{lane_slug}.json": _stable_json(
            _json_parse_list(normalized)
        ),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_no_authorization_drift__{lane_slug}.json": _stable_json(
            _no_authorization_drift_checks(normalized)
        ),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_future_blockers__{lane_slug}.json": _stable_json(
            _future_blocker_register(normalized)
        ),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_pr_body__{lane_slug}.md": _pr_body(normalized, replay=False),
        f"{DEFAULT_REPORT_ROOT_REL}/kt_lane_replay_pr_body__{lane_slug}.md": _pr_body(
            normalized, replay=True
        ),
    }

    contract = {
        "schema_id": SCHEMA_ID,
        "compiler_id": COMPILER_ID,
        "authority": AUTHORITY,
        "status": "PREP_ONLY_SCAFFOLD",
        "prep_only_banner": PREP_ONLY_BANNER,
        "lane_spec": normalized,
        "lane_law_metadata": {
            "lane_kind": normalized["lane_kind"],
            "current_main_head": normalized["current_main_head"],
            "predecessor_outcome": normalized["predecessor_outcome"],
            "selected_outcome": normalized["selected_outcome"],
            "next_lawful_move": normalized["next_lawful_move"],
            "may_authorize": list(normalized["may_authorize"]),
            "must_not_authorize": list(normalized["must_not_authorize"]),
            "authoritative_inputs": list(normalized["authoritative_inputs"]),
            "prep_only_outputs": list(normalized["prep_only_outputs"]),
        },
        "generated_artifacts": sorted(files),
        "files": {path: files[path] for path in sorted(files)},
        "non_authorization_guards": {
            "runtime_authorized": False,
            "r6_open_authorized": False,
            "package_promotion_authorized": False,
            "commercial_claims_authorized": False,
            "forbidden_authority_tokens": list(FORBIDDEN_AUTHORITY_TOKENS),
            "forbidden_authority_context_exempt_fields": sorted(FORBIDDEN_AUTHORITY_CONTEXT_EXEMPT_FIELDS),
        },
    }

    return contract


def compile_lane_spec_file(spec_path: str | Path, output_root: Optional[str | Path] = None) -> Dict[str, Any]:
    try:
        spec = load_no_dupes(Path(spec_path))
    except Exception as exc:  # strict loader raises ValueError for duplicate keys and JSON defects.
        raise LaneSpecError(f"lane spec JSON must parse strictly: {exc}") from exc
    if not isinstance(spec, dict):
        raise LaneSpecError("lane spec JSON must be an object")
    contract = build_lane_contract(spec)
    if output_root is not None:
        root = Path(output_root).resolve()
        for relpath, content in contract["files"].items():
            rel = Path(relpath)
            if rel.is_absolute():
                raise LaneSpecError(f"generated path must be relative: {relpath}")
            target = (root / rel).resolve()
            try:
                target.relative_to(root)
            except ValueError as exc:
                raise LaneSpecError(f"generated path must stay under output root: {relpath}") from exc
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8", newline="\n")
    return contract


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Compile a deterministic PREP_ONLY KT lane scaffold.")
    parser.add_argument("spec", help="Path to lane spec JSON.")
    parser.add_argument("--output-root", help="Optional root where generated files are written.")
    parser.add_argument("--contract-out", help="Optional path for the compiled contract JSON.")
    args = parser.parse_args(argv)

    contract = compile_lane_spec_file(args.spec, args.output_root)
    rendered = _stable_json(contract)
    if args.contract_out:
        target = Path(args.contract_out)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8", newline="\n")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
